Arrays in numpy
ARRAYS-continous memory allocation
Numpy always uses static array and stores only homogenous datas

We have to store the data in the array to use in numpy. So we have to understand that there are 3 types of arrays in numpy
1D array - Vector (only columns)
2D array - Matrix or matrice (Rows and Columns)
3D array - Tensor (Blocks, Rows and Columns)

Before creating an array, we have to observe 2 things
1.Dimensionality
2.Homogenous or Heterogenous datas

#1.Create an array to store the ages of 5 students --> This gives only one piece of information, do 1D array
---> 1 Dimensional Array
---> Homogenous datas

#2.Create an array to store the ages of students belonging to 2 classrooms with 5 students each. --> Gives 2 piece of information,so its 2D array
---> 2 Dimensional Array
---> Homogenous datas
Real world datasets are in the form of matrix only

#3.Create an array to store the ages of students belonging to2 schools having 3 classrooms with 5 students each. --->Gives 3 piece of information, so its 3D array
---> 3 Dimensional Array
---> Homogenous datas

3D array is a combination of multiple 2D arrays combined together

#There are different ways to create arrays in numpy
1.using list
2.using arange() function
3.using zeros() function
4.using ones() function
5.using linspace() function
6.using rand() function

In [4]:
#1.using List --1D array
import numpy as np
l=[1,2,3,4,5]
a=np.array(l)
print(a)

#or

a=np.array([1,45,67,89,39])
print(a)

[1 2 3 4 5]
[ 1 45 67 89 39]


In [10]:
l=np.array([78,48,32,92,37,57])
print(a)

[[78 89 28 40 28]
 [27 79 90 28 67]]


In [3]:
#2D array using list
import numpy as np
a=[[1,2,3,],[1,2,3]]
np.array(a)
print(a)

[[1, 2, 3], [1, 2, 3]]


In [9]:
import numpy as np
a=np.array([[78,89,28,40,28],[27,79,90,28,67]])
print(a)

[[78 89 28 40 28]
 [27 79 90 28 67]]


In [5]:
#2.using arange() --1D array
a=np.arange(2,22,2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


In [7]:
#3.using zeros()  --> 2D array. This takes parameters only as tuple
a=np.zeros((2,2))
print(a)   #Stores data in the of float

[[0. 0.]
 [0. 0.]]


In [8]:
#4.using ones()
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
#5. using linspace()
import numpy as np
arr=np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [6]:
#6. using rand()
import numpy as np
arr=np.random.rand(5)
print(arr)

[0.02068632 0.77828488 0.39234369 0.40830458 0.99209593]


When we create an array in numpy, an array object is being created. This array object consists of the array that has been created along with some instance variables and also methods together called as attributes

The types of instance variables present are
1.shape
2.size
3.ndim
4.dtype

In [7]:
#instance variables inside the array object
#Shape
l=[1,2,3,4,64,89]
a=np.array(l)
print(a.shape)



(6,)


In [10]:
#Size
l=[1,2,3,4,64,89]
a=np.array(l)
print(a.size)

6


In [11]:
#dtype
l=[1,2,3,4,64,89]
a=np.array(l)
print(a.dtype)

int64


In [12]:
#ndim
l=[1,2,3,4,64,89]
a=np.array(l)
print(a.ndim)

1


In [12]:
import numpy as np
a=[[1,2,3,],[1,2,3]]
b=np.array(a)
print(b)
print(b.shape)
print(b.size)
print(b.ndim)
print(b.dtype)

[[1 2 3]
 [1 2 3]]
(2, 3)
6
2
int64


In [14]:
a=np.arange(2,22,2)
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

[ 2  4  6  8 10 12 14 16 18 20]
(10,)
10
1
int64


In [15]:
a=np.zeros((2,2))
print(a) 
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

[[0. 0.]
 [0. 0.]]
(2, 2)
4
2
float64


In [16]:
a=np.ones((3,3))
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)
9
2
float64


In [17]:
import numpy as np
arr=np.linspace(0,1,5)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

[0.   0.25 0.5  0.75 1.  ]
(5,)
5
1
float64


In [18]:
a=np.random.rand(6,2)
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

[[0.31593524 0.70473488]
 [0.66917829 0.16852939]
 [0.62460013 0.93032304]
 [0.00203444 0.67051824]
 [0.49704966 0.77298019]
 [0.52914986 0.90300014]]
(6, 2)
12
2
float64


Sometimes we need only some data from the datasets so indexing and slicing would help to get this

In [20]:
arr=np.array([1,3,5,7,9,2,4,6,8])
print(arr[7])

6


In [21]:
import numpy as np
arr=np.random.rand(100)
print(arr[0:101:1])
print(arr[34:78:4])
print(arr[99:52:-2])
print(arr[::-2])

[0.13950435 0.96346716 0.26641338 0.1009096  0.99094242 0.37790027
 0.78284691 0.93599947 0.91043099 0.23515779 0.24666935 0.84739792
 0.05743443 0.94166017 0.57384863 0.12173992 0.34647883 0.75472586
 0.87566376 0.16483695 0.13669638 0.80809849 0.12235359 0.56076283
 0.91415887 0.87151232 0.13037256 0.34005711 0.72308149 0.50550382
 0.64771571 0.70850549 0.80529008 0.68319669 0.16660166 0.67428916
 0.8998224  0.19255497 0.35636885 0.91137049 0.18492758 0.88711508
 0.66493473 0.32513118 0.18123017 0.85320252 0.54223891 0.6197984
 0.06302269 0.84289611 0.944691   0.52114613 0.30597528 0.58804995
 0.82685728 0.56077893 0.29844523 0.92371657 0.1545837  0.44707783
 0.36644554 0.4328878  0.40253835 0.18897508 0.10093445 0.04446474
 0.16374431 0.3785824  0.61922894 0.33588123 0.10361769 0.51084403
 0.86049866 0.75755555 0.25024667 0.783484   0.68767555 0.10968863
 0.63169555 0.04324199 0.25073375 0.03188226 0.4697935  0.79701651
 0.59982403 0.6637239  0.98467852 0.77675527 0.94153176 0.67048