Arrays in numpy
ARRAYS-continous memory allocation
Numpy always uses static array and stores only homogenous datas

We have to store the data in the array to use in numpy. So we have to understand that there are 3 types of arrays in numpy
1D array - Vector (only columns)
2D array - Matrix or matrice (Rows and Columns)
3D array - Tensor (Blocks, Rows and Columns)

Before creating an array, we have to observe 2 things
1.Dimensionality
2.Homogenous or Heterogenous datas

#1.Create an array to store the ages of 5 students --> This gives only one piece of information, do 1D array
---> 1 Dimensional Array
---> Homogenous datas

#2.Create an array to store the ages of students belonging to 2 classrooms with 5 students each. --> Gives 2 piece of information,so its 2D array
---> 2 Dimensional Array
---> Homogenous datas
Real world datasets are in the form of matrix only

#3.Create an array to store the ages of students belonging to2 schools having 3 classrooms with 5 students each. --->Gives 3 piece of information, so its 3D array
---> 3 Dimensional Array
---> Homogenous datas

3D array is a combination of multiple 2D arrays combined together

#There are different ways to create arrays in numpy
1.using list
2.using arange() function
3.using zeros() function
4.using ones() function

In [4]:
#1.using List --1D array
import numpy as np
l=[1,2,3,4,5]
a=np.array(l)
print(a)

#or

a=np.array([1,45,67,89,39])
print(a)

[1 2 3 4 5]
[ 1 45 67 89 39]


In [5]:
#2.using arange() --1D array
a=np.arange(2,22,2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


In [7]:
#3.using zeros()  --> 2D array. This takes parameters only as tuple
a=np.zeros((2,2))
print(a)   #Stores data in the of float

[[0. 0.]
 [0. 0.]]


In [8]:
#4.using ones()
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
