Arrays in numpy
ARRAYS-continous memory allocation
Numpy always uses static array and stores only homogenous datas

We have to store the data in the array to use in numpy. So we have to understand that there are 3 types of arrays in numpy
1D array - Vector (only columns)
2D array - Matrix or matrice (Rows and Columns)
3D array - Tensor (Blocks, Rows and Columns)

Before creating an array, we have to observe 2 things
1.Dimensionality
2.Homogenous or Heterogenous datas

#1.Create an array to store the ages of 5 students --> This gives only one piece of information, do 1D array
---> 1 Dimensional Array
---> Homogenous datas

#2.Create an array to store the ages of students belonging to 2 classrooms with 5 students each. --> Gives 2 piece of information,so its 2D array
---> 2 Dimensional Array
---> Homogenous datas
Real world datasets are in the form of matrix only

#3.Create an array to store the ages of students belonging to2 schools having 3 classrooms with 5 students each. --->Gives 3 piece of information, so its 3D array
---> 3 Dimensional Array
---> Homogenous datas

3D array is a combination of multiple 2D arrays combined together

#There are different ways to create arrays in numpy
1.using list
2.using arange() function
3.using zeros() function
4.using ones() function
5.using linspace() function
6.using rand() function

In [4]:
#1.using List --1D array
import numpy as np
l=[1,2,3,4,5]
a=np.array(l)
print(a)

#or

a=np.array([1,45,67,89,39])
print(a)

[1 2 3 4 5]
[ 1 45 67 89 39]


In [10]:
l=np.array([78,48,32,92,37,57])
print(a)

[[78 89 28 40 28]
 [27 79 90 28 67]]


In [3]:
#2D array using list
import numpy as np
a=[[1,2,3,],[1,2,3]]
np.array(a)
print(a)

[[1, 2, 3], [1, 2, 3]]


In [9]:
import numpy as np
a=np.array([[78,89,28,40,28],[27,79,90,28,67]])
print(a)

[[78 89 28 40 28]
 [27 79 90 28 67]]


In [5]:
#2.using arange() --1D array
a=np.arange(2,22,2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


In [7]:
#3.using zeros()  --> 2D array. This takes parameters only as tuple
a=np.zeros((2,2))
print(a)   #Stores data in the of float

[[0. 0.]
 [0. 0.]]


In [8]:
#4.using ones()
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
#5. using linspace()
import numpy as np
arr=np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [6]:
#6. using rand()
import numpy as np
arr=np.random.rand(5)
print(arr)

[0.02068632 0.77828488 0.39234369 0.40830458 0.99209593]


When we create an array in numpy, an array object is being created. This array object consists of the array that has been created along with some instance variables and also methods together called as attributes

The types of instance variables present are
1.shape
2.size
3.ndim
4.dtype

In [7]:
#instance variables inside the array object
#Shape
l=[1,2,3,4,64,89]
a=np.array(l)
print(a.shape)



(6,)


In [10]:
#Size
l=[1,2,3,4,64,89]
a=np.array(l)
print(a.size)

6


In [11]:
#dtype
l=[1,2,3,4,64,89]
a=np.array(l)
print(a.dtype)

int64


In [12]:
#ndim
l=[1,2,3,4,64,89]
a=np.array(l)
print(a.ndim)

1


In [12]:
import numpy as np
a=[[1,2,3,],[1,2,3]]
b=np.array(a)
print(b)
print(b.shape)
print(b.size)
print(b.ndim)
print(b.dtype)

[[1 2 3]
 [1 2 3]]
(2, 3)
6
2
int64


In [14]:
a=np.arange(2,22,2)
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

[ 2  4  6  8 10 12 14 16 18 20]
(10,)
10
1
int64


In [15]:
a=np.zeros((2,2))
print(a) 
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

[[0. 0.]
 [0. 0.]]
(2, 2)
4
2
float64


In [16]:
a=np.ones((3,3))
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)
9
2
float64


In [17]:
import numpy as np
arr=np.linspace(0,1,5)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

[0.   0.25 0.5  0.75 1.  ]
(5,)
5
1
float64


In [18]:
a=np.random.rand(6,2)
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

[[0.31593524 0.70473488]
 [0.66917829 0.16852939]
 [0.62460013 0.93032304]
 [0.00203444 0.67051824]
 [0.49704966 0.77298019]
 [0.52914986 0.90300014]]
(6, 2)
12
2
float64


SLICING AND INDEXING

Sometimes we need only some data from the datasets so indexing and slicing would help to get this. We can do this even in 2D and 3D Arrays also.

In [6]:
arr=np.array([1,3,5,7,9,2,4,6,8])
print(arr[7])

arr=np.array([1,3,5,7,9,2,4,6,8])
print(arr[-7])

6
5


In [4]:
import numpy as np
arr=np.random.rand(100)
print(arr[0:101:1])
print(arr[34:78:4])
print(arr[99:52:-2])
print(arr[::-2])

[0.7312489  0.67445807 0.14476001 0.19431209 0.94631932 0.89573144
 0.50224424 0.86220296 0.743      0.07118573 0.60588062 0.28894195
 0.60099798 0.93255029 0.62693727 0.00593296 0.61473839 0.39784868
 0.53585181 0.89308197 0.01154381 0.84022871 0.24255949 0.33279134
 0.93416064 0.57281422 0.57940317 0.60060507 0.25082352 0.36006163
 0.55951454 0.62263776 0.4058638  0.06680957 0.01157058 0.22223798
 0.05782246 0.735665   0.33797132 0.6649191  0.62069296 0.69500376
 0.47462378 0.58895662 0.31515272 0.71362272 0.52718909 0.96080216
 0.02828558 0.85232752 0.48021047 0.06816941 0.78525729 0.11336972
 0.91812613 0.80932628 0.05290088 0.55205328 0.38721067 0.5742744
 0.16741775 0.98809591 0.0888421  0.26260002 0.89805234 0.006342
 0.34775055 0.39907665 0.28760991 0.94274696 0.68814797 0.47432849
 0.45056707 0.39704581 0.08463479 0.92856515 0.32153765 0.13539666
 0.10035064 0.52039408 0.67041261 0.31079477 0.54401835 0.62736581
 0.38246892 0.9024864  0.96953734 0.83463578 0.33791678 0.6405782

In [14]:
#When it comes to 2D we should give both rows and columns separated by comma
import numpy as np
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr[1][1])
print(arr[1,1])
print(arr[:,1]) #rows,colums
print(arr[2,:])

5
5
[2 5 8]
[7 8 9]


In [18]:
#To get a particular data, we can use this
import numpy as np
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr[1:3,1:3])
print(arr[1:,1:])

[[5 6]
 [8 9]]
[[5 6]
 [8 9]]


VECTOR,MATRIX MATHEMATICS

In [49]:
#Vectorization of numpy - vector mathematics
#When we are adding the 2 vectors,there should be same number of columns.
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1+arr2)  

import numpy as np
arr1=np.array([6,4,8])
arr2=np.array([4,5,6])
print(arr1-arr2)  

print(arr1*arr2)
print(arr1/arr2)
print(arr1//arr2)
print(arr1**arr2)

#We will get error in this because of different no.of columns in both the vectors
arr1=np.array([1,2,3])
arr2=np.array([4,5,6,9,7,0])
print(arr1+arr2) 




[5 7 9]
[ 2 -1  2]
[24 20 48]
[1.5        0.8        1.33333333]
[1 0 1]
[  1296   1024 262144]


ValueError: operands could not be broadcast together with shapes (3,) (6,) 

In [22]:
#Matrix
arr1=np.array([[1,2,3],
               [4,5,6]])
arr2=np.array([[40,50,60],
               [34,23,56]])
print(arr1+arr2) 

#one is matrix and the other is vector,but the vectors gets added to both the rows of the matrix.
#Broadcast in numpy
arr1=np.array([[1,2,3],
               [4,5,6]])
arr2=np.array([40,50,60])  #Adds in both the rows of matrix - Broadcasting
print(arr1+arr2)

[[41 52 63]
 [38 28 62]]
[[41 52 63]
 [44 55 66]]


STANDARDIZATION IN NUMPY

In [31]:
#Maths on vectors
#Sometimes we need to standardize the datas that are present in the datasets. So we can apply +,-,*./,//,%,** as we need
import numpy as np
arr1=np.array([1,2,3,4])
print(arr1-3)
print(arr1+6)
print(arr1%2)
print(arr1**4)

#We can also perform also each values if we need separately
import numpy as np
arr1=np.array([0.03,0.1,10,0.5])
arr=np.array([10,10,0,10])
print(arr1+arr)

[-2 -1  0  1]
[ 7  8  9 10]
[1 0 1 0]
[  1  16  81 256]
[10.03 10.1  10.   10.5 ]


AGGREGATION IN NUMPY
1.Max()
2.Min()
3.Sum()
4.Mean()
5.Std()

In [35]:
arr=np.array([1,2,3,4,5,6])
max(arr)

np.int64(6)

In [43]:
arr=np.array([1,2,3,4,5,6])
print(max(arr))
print(np.max(arr))
print(arr.max())
print(arr.min())
print(arr.sum())
print(arr.mean()) #Average of the datas in the array
print(arr.std())  #standard deviation(How each data is deviated from the other data)

6
6
6
1
21
3.5
1.707825127659933
